In [3]:
!pip install opencv-python

In [ ]:
import cv2
img1=cv2.imread(r"C:\Users\lenovo\Downloads\index9.jpg")
img1=cv2.resize(img1,(1280,700))
print(img1)
cv2.imshow("original",img1)
cv2.waitKey()
cv2.destroyAllWindows()

In [ ]:
import cv2
img2=cv2.imread(r"C:\Users\lenovo\Downloads\index9.jpg",0)
img2=cv2.resize(img2,(1280,700))
print(img2)
cv2.imshow("original",img2)
cv2.waitKey()
cv2.destroyAllWindows()

[[113 113 113 ...  98  98  98]
 [113 113 113 ...  98  98  98]
 [113 113 113 ...  98  98  98]
 ...
 [ 92  92  92 ...  67  67  67]
 [ 91  91  91 ...  72  72  72]
 [ 73  73  73 ...  57  57  57]]


In [ ]:
import cv2
img3=cv2.imread(r"C:\Users\lenovo\Downloads\index9.jpg",-1)
img3=cv2.resize(img3,(1280,700))
cv2.imshow("Unchanged Image",img3)
print("Image in original value==\n",img3)
cv2.waitKey(0)
cv2.destroyAllWindows()

Image in original value==
 [[[ 86 122 105]
  [ 86 122 105]
  [ 86 122 105]
  ...
  [ 75 114  76]
  [ 75 114  76]
  [ 75 114  76]]

 [[ 86 122 105]
  [ 86 122 105]
  [ 86 122 105]
  ...
  [ 75 114  76]
  [ 75 114  76]
  [ 75 114  76]]

 [[ 86 122 105]
  [ 86 122 105]
  [ 86 122 105]
  ...
  [ 75 114  76]
  [ 75 114  76]
  [ 75 114  76]]

 ...

 [[ 79 103  75]
  [ 79 103  75]
  [ 79 103  75]
  ...
  [ 65  76  50]
  [ 65  76  50]
  [ 65  76  50]]

 [[ 78 101  73]
  [ 78 101  73]
  [ 78 101  73]
  ...
  [ 70  81  55]
  [ 70  81  55]
  [ 70  81  55]]

 [[ 61  84  56]
  [ 61  84  56]
  [ 61  84  56]
  ...
  [ 55  66  40]
  [ 55  66  40]
  [ 55  66  40]]]


In [2]:
import cv2
import numpy as np

def cross(x):
    pass
#create a black imgae
img = np.zeros((300,512,3),np.uint8) #empty image
cv2.namedWindow("Color Picker")

#Creating switch for on and of the trackbars
switch = '0 : OFF \n1 : ON'
cv2.createTrackbar(switch, 'Color Picker',0,1,cross)

#Creating TrackBars For Adjusting Colors
cv2.createTrackbar("R","Color Picker",0,255,cross)
cv2.createTrackbar("G","Color Picker",0,255,cross)
cv2.createTrackbar("B","Color Picker",0,255,cross)

#Now creating logic to handle trackbars
while True:
    cv2.imshow("Color Picker",img)
    k = cv2.waitKey(1) & 0xFF
    if k==27: #for exit
        break
    
    #set current positions of four bars
    s = cv2.getTrackbarPos(switch,"Color Picker") #switch
    r = cv2.getTrackbarPos("R","Color Picker")
    g = cv2.getTrackbarPos("G","Color Picker")
    b = cv2.getTrackbarPos("B","Color Picker")
    
    if s==0:
        img[:] = 0
    else:
        img[:] = [r,g,b] #here openCV support BGR
cv2.destroyAllWindows()

error: OpenCV(4.7.0) D:\a\opencv-python\opencv-python\opencv\modules\highgui\src\window_w32.cpp:2576: error: (-27:Null pointer) NULL window: 'Color Picker' in function 'cvGetTrackbarPos'


In [ ]:
path=input()